### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by tlin-taolin** [LINs-lab/cluster_tutorial#2] opened 2022-12-03 17:28 UTC
it is ok to use 
```bash
ssh taolin@10.0.2.162
```
to access the node, but it is not the case for 
```bash
ssh -p 22332  taolin@login.lins.lab
```

**Comment by DmitriZhao** [comment] 2022-12-05 12:21
Duplicate of #1 
P.S. There will be a major update after the arrival of the storage/management node, on which we will migrate and reconfigure the login node, then the user system and NFS share will be double-checked and documented. Closing this for now.

**Closed by DmitriZhao** 2022-12-05 12:21 UTC
