### ISSUE TITLE
determinedAI notebook start error

### ISSUE THREAD

**Issue by haobo-song** [LINs-lab/cluster_tutorial#6] opened 2022-12-12 21:37 UTC
Hello, when I use VPN connection, I failed to open jupyter notebook through 

> det notebook start --config-file config.yaml

By this command, a new notebook is created and I can find the task by 

> det task

However, I cannot open this notebook by the link it shows in chrome.
Error message: ERR_CONNECTION_TIMED_OUT
Command I use:
```
haobosong@lins-loginnode:~$ det notebook start --config-file config.yaml 
Warning: The requested job requires more slots than currently available. You may need to increase cluster resources in order for the job to run.
Scheduling test_haobo (id: 88bd82d4-ef47-4904-83ff-5beb8bedb660)...
test_haobo was assigned to an agent...
Resources for test_haobo has started...
Unable to connect to VS Code server: Error in request.
Error: connect ENOENT /run/user/1004/vscode-ipc-0f939929-b954-4d30-9822-4b56f3c26973.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1004/vscode-ipc-0f939929-b954-4d30-9822-4b56f3c26973.sock'
}
Jupyter Notebook is running at: http://192.168.123.168:8080/det/interactive/88bd82d4-ef47-4904-83ff-5beb8bedb660/notebook/test_haobo/64c128t_512_3090/%2Fdet%2Fwait%2Fnotebook%2F88bd82d4-ef47-4904-83ff-5beb8bedb660%3FeventUrl%3D%2Fproxy%2F88bd82d4-ef47-4904-83ff-5beb8bedb660%2F%2Fnotebooks%2F88bd82d4-ef47-4904-83ff-5beb8bedb660%2Fevents%26serviceAddr%3D%2Fproxy%2F88bd82d4-ef47-4904-83ff-5beb8bedb660%2F?currentSlotsExceeded=true
```

By the way, this error can be eliminated when using terminal to connect ssh instead of vscode, but I still cannot open notebook.

Do you have some solution? Thank you!

**Comment by DmitriZhao** [comment] 2022-12-13 06:58
I think this is a Duplicate of #5.

**Closed** 2022-12-15 10:21 UTC
